CREATE TABLE tb_Edital (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    Titulo VARCHAR(255) NOT NULL,
    Numero INT NOT NULL,
    Ano INT NOT NULL,

    inicioSubmissao DATE NOT NULL,
    fimSubmissao DATE NOT NULL,

    inicioAvaliacao DATE NOT NULL,
    fimAvaliacao DATE NOT NULL

);