CREATE TABLE tb_roles (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name    VARCHAR(50) NOT NULL,

    CONSTRAINT pk_tb_roles PRIMARY KEY (id)
);

CREATE TABLE tb_users (
      id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
      cpf          VARCHAR(14) NOT NULL,
      nome         VARCHAR(100) NOT NULL,
      nome_social  VARCHAR(100),
      email        VARCHAR(100) NOT NULL UNIQUE,
      password     VARCHAR(255) NOT NULL,
      campus       VARCHAR(100) NOT NULL,
      formacao     VARCHAR(100) NOT NULL,
      titulacao    VARCHAR(100) NOT NULL,
      sexo         VARCHAR(20),
      lattes       VARCHAR(255),
      telefone     VARCHAR(20),

    CONSTRAINT pk_tb_users PRIMARY KEY (id)
);

CREATE TABLE tb_user_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT,
    role_id BIGINT,

    CONSTRAINT pk_tb_user_role PRIMARY KEY (id),
    CONSTRAINT fk_user_id
        FOREIGN KEY (user_id)
        REFERENCES tb_users(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_role_id
        FOREIGN KEY (role_id)
        REFERENCES tb_roles(id)
);

CREATE TABLE tb_edital (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    titulo VARCHAR(255),
    numero INT NOT NULL,
    ano INT NOT NULL,
    inicio_submissao DATE,
    fim_submissao DATE,
    inicio_avaliacao DATE,
    fim_avaliacao DATE,

    CONSTRAINT pk_tb_edital PRIMARY KEY (id)
);

INSERT INTO tb_roles (name) VALUES ('ROLE_COORDENADOR');
INSERT INTO tb_roles (name) VALUES ('ROLE_AVALIADOR');